import Images from "../../../Assets/Images"

export const DailyBestSellsData = [
  {
    discount: "Save 35%",
    discountBG: "#d4f2e5",
    image: Images.Coconut,
    brand: "Hodo Foods",
    title: "All Natural Italian-Style Chicken Meatballs",
    rating: 1,
    price: 238.85,
    oldPrice: 245.8,
    sold: 90,
    total: 120,
  },
  {
    discount: "Sale",
    discountBG: "#d6eaff",
    image: Images.Metaballs,
    brand: "Hodo Foods",
    title: "Angie’s Boomchickapop Sweet and Wormnies",
    rating: 1,
    price: 238.85,
    oldPrice: 245.8,
    sold: 90,
    total: 120,
  },
  {
    discount: "Best sale",
    discountBG: "#ffe6cd",
    image: Images.VegPops,
    brand: "Hodo Foods",
    title: "Foster Farms Takeout Crispy Classic Veg Pops",
    rating: 1,
    price: 238.85,
    oldPrice: 245.8,
    sold: 90,
    total: 120,
  },
  {
    discount: "Save 15%",
    discountBG: "#ffd6df",
    image: Images.BeanNut,
    brand: "Hodo Foods",
    title: "Blue Diamond Almonds Lightly Salted",
    rating: 1,
    price: 238.85,
    oldPrice: 245.8,
    sold: 90,
    total: 120,
  },
];
