import Images from '../Assets/Images';

const PopularProductData = [
  {
    id: 1,
    discount: 'HOT',
    discountBG: '#F74B81',
    image: Images.Seeds,
    category: 'Snack',
    title: 'Seeds of Change Organic Quinoe',
    rating: 4.0,
    brand: 'NestFood',
    price: '28.85',
    oldPrice: '32.8',
  },
  {
    id: 2,
    discount: 'Sale',
    discountBG: '#67BCEE',
    image: Images.Metaballs,
    category: 'Hodo Foods',
    title: 'All Natural Italian Style Chicken Meatballs',
    rating: 3.5,
    brand: 'Stouffer',
    price: '52.85',
    oldPrice: '55.8',
  },
  {
    id: 3,
    discount: 'New',
    discountBG: '#3BB77E',
    image: Images.VegPops,
    category: 'Snack',
    title: 'Angie’s Boomchickapop Sweet & Salty',
    rating: 4.0,
    brand: 'StarKist',
    price: '48.85',
    oldPrice: '52.8',
  },
  {
    id: 4,
    discount: '',
    discountBG: '',
    image: Images.BeanNut,
    category: 'Vegetables',
    title: 'Foster Farms Takeout Crispy Classic',
    rating: 4.0,
    brand: 'NestFood',
    price: '17.85',
    oldPrice: '19.8',
  },
  {
    id: 5,
    discount: '-14%',
    discountBG: '#F59758',
    image: Images.Coconut,
    category: 'Pet Foods',
    title: 'Blue Diamond almonds Lightly',
    rating: 4.0,
    brand: 'Nest Food',
    price: '23.85',
    oldPrice: '25.8',
  },
  {
    id: 6,
    discountBG: '',
    discountBgColor: '',
    image: Images.Muffin,
    category: 'Hodo Foods',
    title: 'Chobani Complete Vanilla Greek',
    rating: 4.0,
    brand: 'NestFood',
    price: '54.85',
    oldPrice: '55.8',
  },
  {
    id: 7,
    discount: '',
    discountBG: '',
    image: Images.Butter,
    category: 'Meals',
    title: 'Canada Dry Ginger Ale - 2L Bottle',
    rating: 4.0,
    brand: 'Nest Food',
    price: '32.85',
    oldPrice: '33.8',
  },
  {
    id: 8,
    discount: 'Sale',
    discountBG: '#67BCEE',
    image: Images.Cream,
    category: 'Snack',
    title: 'Encore Seafoods Stuffed Alaskan',
    rating: 4.0,
    brand: 'Nest Food',
    price: '35.85',
    oldPrice: '37.8',
  },
  {
    id: 9,
    discount: 'Hot',
    discountBG: '#F74B81',
    image: Images.OrganicCoffee,
    category: 'Coffees',
    title: 'Gortons Beer Battered Fish Fillets',
    rating: 4.0,
    brand: 'Old El Paso',
    price: '23.85',
    oldPrice: '25.8',
  },
  {
    id: 10,
    discount: '',
    discountBG: '',
    image: Images.Latte,
    category: 'Cream',
    title: 'Haagen-Dazs Caramel Cone Ice Cream',
    rating: 2.0,
    brand: 'Tyson',
    price: '22.85',
    oldPrice: '24.8',
  }
];

export default PopularProductData;
