import Images from "../Assets/Images";

const PopularProductData = [
  {
    id: 1,
    discount: "HOT",
    discountBG: "#F74B81",
    image: Images.Seeds,
    category: "Snack",
    title: "Seeds of Change Organic Quinoe",
    rating: 4.0,
    brand: "NestFood",
    weight: "450g",
    price: "28.85",
    oldPrice: "32.8",
    text: "Organic quinoa packed with fiber and essential nutrients for healthy meals.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nam beatae consectetur, atque inventore aliquam adipisci   perspiciatis nostrum qui consequatur praesentium?",
  },
  {
    id: 2,
    discount: "Sale",
    discountBG: "#67BCEE",
    image: Images.Metaballs,
    category: "Hodo Foods",
    title: "All Natural Italian Style Chicken Meatballs",
    rating: 3.5,
    brand: "Stouffer",
    weight: "1kg",
    price: "52.85",
    oldPrice: "55.8",
    text: "Juicy, all-natural chicken meatballs seasoned with classic Italian herbs.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nam beatae consectetur, atque inventore aliquam adipisciperspiciatis nostrum qui consequatur praesentium?",
  },
  {
    id: 3,
    discount: "New",
    discountBG: "#3BB77E",
    image: Images.VegPops,
    category: "Snack",
    title: "Angies Boomchickapop Sweet & Salty",
    rating: 4.0,
    brand: "StarKist",
    weight: "160g",
    price: "48.85",
    oldPrice: "52.8",
    text: "A delicious blend of sweet and salty popcorn made with whole grains.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nam beatae consectetur, atque inventore aliquam adipisciperspiciatis nostrum qui consequatur praesentium?",
  },
  {
    id: 4,
    discount: "",
    discountBG: "",
    image: Images.BeanNut,
    category: "Vegetables",
    title: "Foster Farms Takeout Crispy Classic",
    rating: 4.0,
    brand: "NestFood",
    weight: "600g",
    price: "17.85",
    oldPrice: "19.8",
    text: "Crispy and savory veggie delight perfect for quick meals or snacks.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nam beatae consectetur, atque inventore aliquam adipisci  perspiciatis nostrum qui consequatur praesentium?",
  },
  {
    id: 5,
    discount: "-14%",
    discountBG: "#F59758",
    image: Images.Coconut,
    category: "Pet Foods",
    title: "Blue Diamond almonds Lightly",
    rating: 4.0,
    brand: "Nest Food",
    weight: "200g",
    price: "23.85",
    oldPrice: "25.8",
    text: "Lightly salted almonds, great as a healthy and crunchy snack option.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nam beatae consectetur, atque inventore aliquam adipisciperspiciatis nostrum qui consequatur praesentium?",
  },
  {
    id: 6,
    discount: "",
    discountBG: "",
    image: Images.Muffin,
    category: "Hodo Foods",
    title: "Chobani Complete Vanilla Greek",
    rating: 4.0,
    brand: "NestFood",
    weight: "170g",
    price: "54.85",
    oldPrice: "55.8",
    text: "High-protein Greek yogurt with a creamy vanilla flavor and no added sugar.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nam beatae consectetur, atque inventore aliquam adipisciperspiciatis nostrum qui consequatur praesentium?",
  },
  {
    id: 7,
    discount: "",
    discountBG: "",
    image: Images.Butter,
    category: "Meals",
    title: "Canada Dry Ginger Ale - 2L Bottle",
    rating: 4.0,
    brand: "Nest Food",
    weight: "2L",
    price: "32.85",
    oldPrice: "33.8",
    text: "Refreshing ginger ale perfect for pairing with meals or drinking solo.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nam beatae consectetur, atque inventore aliquam adipisci  perspiciatis nostrum qui consequatur praesentium?",
  },
  {
    id: 8,
    discount: "Sale",
    discountBG: "#67BCEE",
    image: Images.Cream,
    category: "Snack",
    title: "Encore Seafoods Stuffed Alaskan",
    rating: 4.0,
    brand: "Nest Food",
    weight: "500g",
    price: "35.85",
    oldPrice: "37.8",
    text: "Flavorful seafood stuffed with rich Alaskan filling and natural ingredients.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nam beatae consectetur, atque inventore aliquam adipisci  perspiciatis nostrum qui consequatur praesentium?",
  },
  {
    id: 9,
    discount: "Hot",
    discountBG: "#F74B81",
    image: Images.OrganicCoffee,
    category: "Coffees",
    title: "Gortons Beer Battered Fish Fillets",
    rating: 4.0,
    brand: "Old El Paso",
    weight: "900g",
    price: "23.85",
    oldPrice: "25.8",
    text: "Crispy beer-battered fish fillets perfect for lunch or dinner dishes.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nam beatae consectetur, atque inventore aliquam adipisci  perspiciatis nostrum qui consequatur praesentium?",
  },
  {
    id: 10,
    discount: "",
    discountBG: "",
    image: Images.Latte,
    category: "Cream",
    title: "Haagen-Dazs Caramel Cone Ice Cream",
    rating: 2.0,
    brand: "Tyson",
    weight: "473 mL",
    price: "22.85",
    oldPrice: "24.8",
    text: "Decadent caramel ice cream loaded with crunchy chocolate-coated cone pieces.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nam beatae consectetur, atque inventore aliquam adipisci  perspiciatis nostrum qui consequatur praesentium?",
  },
  {
    id: 11,
    discount: "HOT",
    discountBG: "#F74B81",
    image: Images.Seeds,
    category: "Snack",
    title: "Seeds of Change Organic Quinoe",
    rating: 4.0,
    brand: "NestFood",
    weight: "450 g",
    price: "28.85",
    oldPrice: "32.8",
    text: "Organic quinoa packed with fiber and essential nutrients for healthy meals.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nam beatae consectetur, atque inventore aliquam adipiscperspiciatis nostrum qui consequatur praesentium?",
  },
  {
    id: 12,
    discount: "Sale",
    discountBG: "#67BCEE",
    image: Images.Metaballs,
    category: "Hodo Foods",
    title: "All Natural Italian Style Chicken Meatballs",
    rating: 3.5,
    brand: "Stouffer",
    weight: "1 kg",
    price: "52.85",
    oldPrice: "55.8",
    text: "Juicy, all-natural chicken meatballs seasoned with classic Italian herbs.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nam beatae consectetur, atque inventore aliquam adipisci  perspiciatis nostrum qui consequatur praesentium?",
  },
  {
    id: 13,
    discount: "New",
    discountBG: "#3BB77E",
    image: Images.VegPops,
    category: "Snack",
    title: "Angies Boomchickapop Sweet & Salty",
    rating: 4.0,
    brand: "StarKist",
    weight: "160 g",
    price: "48.85",
    oldPrice: "52.8",
    text: "A delicious blend of sweet and salty popcorn made with whole grains.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nam beatae consectetur, atque inventore aliquam adipisci  perspiciatis nostrum qui consequatur praesentium?",
  },
  {
    id: 14,
    discount: "",
    discountBG: "",
    image: Images.BeanNut,
    category: "Vegetables",
    title: "Foster Farms Takeout Crispy Classic",
    rating: 4.0,
    brand: "NestFood",
    weight: "600 g",
    price: "17.85",
    oldPrice: "19.8",
    text: "Crispy and savory veggie delight perfect for quick meals or snacks.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nam beatae consectetur, atque inventore aliquam adipisci  perspiciatis nostrum qui consequatur praesentium?",
  },
  {
    id: 15,
    discount: "-14%",
    discountBG: "#F59758",
    image: Images.Coconut,
    category: "Pet Foods",
    title: "Blue Diamond almonds Lightly",
    rating: 4.0,
    brand: "Nest Food",
    weight: "200 g",
    price: "23.85",
    oldPrice: "25.8",
    text: "Lightly salted almonds, great as a healthy and crunchy snack option.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nam beatae consectetur, atque inventore aliquam adipisci  perspiciatis nostrum qui consequatur praesentium?",
  },
  {
    id: 16,
    discount: "",
    discountBG: "",
    image: Images.Muffin,
    category: "Hodo Foods",
    title: "Chobani Complete Vanilla Greek",
    rating: 4.0,
    brand: "NestFood",
    weight: "170 g",
    price: "54.85",
    oldPrice: "55.8",
    text: "High-protein Greek yogurt with a creamy vanilla flavor and no added sugar.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nam beatae consectetur, atque inventore aliquam adipisci  perspiciatis nostrum qui consequatur praesentium?",
  },
  {
    id: 17,
    discount: "",
    discountBG: "",
    image: Images.Butter,
    category: "Meals",
    title: "Canada Dry Ginger Ale - 2L Bottle",
    rating: 4.0,
    brand: "Nest Food",
    weight: "2 L",
    price: "32.85",
    oldPrice: "33.8",
    text: "Refreshing ginger ale perfect for pairing with meals or drinking solo.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nam beatae consectetur, atque inventore aliquam adipisci  perspiciatis nostrum qui consequatur praesentium?",
  },
  {
    id: 18,
    discount: "Sale",
    discountBG: "#67BCEE",
    image: Images.Cream,
    category: "Snack",
    title: "Encore Seafoods Stuffed Alaskan",
    rating: 4.0,
    brand: "Nest Food",
    weight: "500 g",
    price: "35.85",
    oldPrice: "37.8",
    text: "Flavorful seafood stuffed with rich Alaskan filling and natural ingredients.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nam beatae consectetur, atque inventore aliquam adipisci  perspiciatis nostrum qui consequatur praesentium?",
  },
  {
    id: 19,
    discount: "Hot",
    discountBG: "#F74B81",
    image: Images.OrganicCoffee,
    category: "Coffees",
    title: "Gortons Beer Battered Fish Fillets",
    rating: 4.0,
    brand: "Old El Paso",
    weight: "900 g",
    price: "23.85",
    oldPrice: "25.8",
    text: "Crispy beer-battered fish fillets perfect for lunch or dinner dishes.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nam beatae consectetur, atque inventore aliquam adipisci  perspiciatis nostrum qui consequatur praesentium?",
  },
  {
    id: 20,
    discount: "",
    discountBG: "",
    image: Images.Latte,
    category: "Cream",
    title: "Haagen-Dazs Caramel Cone Ice Cream",
    rating: 2.0,
    brand: "Tyson",
    weight: "473 mL",
    price: "22.85",
    oldPrice: "24.8",
    text: "Decadent caramel ice cream loaded with crunchy chocolate-coated cone pieces.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nam beatae consectetur, atque inventore aliquam adipisci  perspiciatis nostrum qui consequatur praesentium?",
  },
];

export default PopularProductData;
