import Images from "../Assets/Images";

const PopularProductData = [
  {
    id: 1,
    sku: "SN-001",
    image: Images.Seeds,
    image2: Images.Metaballs,
    image3: Images.VegPops,
    category: "Milks & Dairies",
    title: "Seeds of Change Organic Quinoa",
    rating: 4.0,
    brand: "NestFood",
    weight: "450g",
    price: "288.85",
    oldPrice: "323.80",
    discount: "HOT",
    discountBG: "#F74B81",
    stockStatus: "Out of Stock",
    tags: ["organic", "quinoa", "fiber"],
    text: "Organic quinoa packed with fiber and essential nutrients.",
    longDescription: "This organic quinoa is perfect for a healthy lifestyle. Rich in fiber and essential nutrients, it can be served with vegetables or used in salads and other dishes.",
    shippingInfo: "Free shipping for orders over $50"
  },
  {
    id: 2,
    sku: "HD-002",
    image: Images.Metaballs,
    image2: Images.Seeds,
    image3: Images.Coconut,
    category: "clothing",
    title: "Italian Style Chicken Meatballs",
    rating: 3.5,
    brand: "Stouffer",
    weight: "1kg",
    price: "529.85",
    oldPrice: "559.80",
    discount: "Sale",
    discountBG: "#67BCEE",
    stockStatus: "In Stock",
    tags: ["meatballs", "chicken", "italian"],
    text: "Juicy, all-natural chicken meatballs seasoned with Italian herbs.",
    longDescription: "Our meatballs are made from natural chicken, seasoned with Italian spices, and ideal for pasta dishes or as a quick protein snack.",
    shippingInfo: "Standard shipping charges apply."
  },
  {
    id: 3,
    sku: "SN-003",
    image: Images.VegPops,
    image2: Images.BeanNut,
    image3: Images.Butter,
    category: "Pet Food",
    title: "Boomchickapop Sweet & Salty Popcorn",
    rating: 4.0,
    brand: "StarKist",
    weight: "160g",
    price: "1482.85",
    oldPrice: "1520.80",
    discount: "New",
    discountBG: "#3BB77E",
    stockStatus: "In Stock",
    tags: ["popcorn", "sweet", "salty"],
    text: "A delicious blend of sweet and salty popcorn.",
    longDescription: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti obcaecati quam at ratione itaque inventore harum animi architecto, corporis, veniam ut, cumque suscipit? Modi magni amet praesentium reiciendis? Distinctio, nostrum? Voluptas est aspernatur architecto omnis enim. Aspernatur saepe, veniam laborum veritatis neque rerum accusantium doloremque reiciendis. Nulla autem minima, odit porro modi quis a aut, laudantium cum soluta placeat molestias. Voluptatibus consequuntur similique nisi aspernatur, facere necessitatibus ratione quisquam voluptas veniam aliquid repudiandae atque sint molestiae tenetur commodi soluta neque corporis modi accusamus quam ea? Eligendi ducimus omnis quae ex. Quisquam eligendi, aperiam amet minus, dolores, veniam quasi molestias laborum dicta adipisci dolorum sed neque! Ad assumenda vitae, perspiciatis tenetur ut cum soluta veniam minus magnam maxime dolore impedit culpa. Qui, rerum tempore ratione pariatur cupiditate cumque voluptatibus soluta quam? Quia nam culpa aliquid fuga aut ut ullam laudantium perferendis tempore. Eos deleniti praesentium tempora veniam repudiandae aut quaerat recusandae!",
    shippingInfo: "Free delivery on first order"
  },
  {
    id: 4,
    sku: "VE-004",
    image: Images.BeanNut,
    image2: Images.Coconut,
    image3: Images.Metaballs,
    category: "Vegetables",
    title: "Foster Farms Crispy Classic",
    rating: 4.0,
    brand: "Baking material",
    weight: "600g",
    price: "1770.85",
    oldPrice: "1900.80",
    discount: "",
    discountBG: "",
    stockStatus: "Out of Stock",
    tags: ["veggie", "crispy", "snack"],
    text: "Crispy veggie bites, perfect for quick meals.",
    longDescription: "Foster Farms brings a crispy and savory delight packed with flavors. Serve with sauces or enjoy as-is.",
    shippingInfo: "Restocking soon"
  },
  {
    id: 5,
    sku: "PT-005",
    image: Images.Coconut,
    image2: Images.Seeds,
    image3: Images.Muffin,
    category: "Pet Foods",
    title: "Blue Diamond Lightly Salted Almonds",
    rating: 4.0,
    brand: "Nest Food",
    weight: "200g",
    price: "231.85",
    oldPrice: "250.80",
    discount: "-14%",
    discountBG: "#F59758",
    stockStatus: "In Stock",
    tags: ["almonds", "healthy", "snack"],
    text: "Lightly salted almonds, perfect for guilt-free snacking.",
    longDescription: "Packed with protein and healthy fats, these almonds are ideal for midday snacks or on-the-go munching.",
    shippingInfo: "Express shipping available"
  },
  {
    id: 6,
    sku: "HD-006",
    image: Images.Muffin,
    image2: Images.Butter,
    image3: Images.VegPops,
    category: "Fresh Fruit",
    title: "Chobani Complete Vanilla Greek Yogurt",
    rating: 4.0,
    brand: "NestFood",
    weight: "170g",
    price: "547.85",
    oldPrice: "1055.80",
    discount: "",
    discountBG: "",
    stockStatus: "In Stock",
    tags: ["yogurt", "greek", "protein"],
    text: "High-protein vanilla yogurt with no added sugar.",
    longDescription: "Chobani's Complete Vanilla yogurt is smooth, rich, and fortified with probiotics for better digestion and health.",
    shippingInfo: "Refrigerated shipping ensured"
  },
  {
    id: 7,
    sku: "ML-007",
    image: Images.Butter,
    image2: Images.Cream,
    image3: Images.OrganicCoffee,
    category: "Meals",
    title: "Canada Dry Ginger Ale - 2L Bottle",
    rating: 4.0,
    brand: "Milks & Dairies",
    weight: "2L",
    price: "1320.85",
    oldPrice: "1330.80",
    discount: "",
    discountBG: "",
    stockStatus: "In Stock",
    tags: ["beverage", "ginger", "carbonated"],
    text: "Refreshing ginger ale perfect for meals or solo drinking.",
    longDescription: "Canada Dry brings a bold ginger flavor that's both refreshing and crisp—great for mixers or on its own.",
    shippingInfo: "Available for local delivery"
  },
  {
    id: 8,
    sku: "SK-008",
    image: Images.Cream,
    image2: Images.BeanNut,
    image3: Images.Latte,
    category: "Snack",
    title: "Encore Seafoods Stuffed Alaskan",
    rating: 4.0,
    brand: "Clothing",
    weight: "500g",
    price: "350.85",
    oldPrice: "370.80",
    discount: "Sale",
    discountBG: "#67BCEE",
    stockStatus: "Limited Stock",
    tags: ["seafood", "stuffed", "alaskan"],
    text: "Flavorful seafood stuffed with rich Alaskan filling.",
    longDescription: "Stuffed Alaskan seafood treats are packed with herbs, breadcrumbs, and a creamy filling that melts in your mouth.",
    shippingInfo: "Ships in insulated packaging"
  },
  {
    id: 9,
    sku: "CO-009",
    image: Images.OrganicCoffee,
    image2: Images.Cream,
    image3: Images.Seeds,
    category: "Milks & Dairies",
    title: "Gortons Beer Battered Fish Fillets",
    rating: 4.0,
    brand: "Old El Paso",
    weight: "900g",
    price: "2000.00",
    oldPrice: "2500.80",
    discount: "Hot",
    discountBG: "#F74B81",
    stockStatus: "In Stock",
    tags: ["fish", "beer battered", "frozen"],
    text: "Crispy beer-battered fish fillets for lunch or dinner.",
    longDescription: "Golden and crunchy, Gortons beer-battered fillets are ideal for tacos, sandwiches, or as a main dish.",
    shippingInfo: "Frozen delivery option required"
  },
  {
    id: 10,
    sku: "C-010",
    image: Images.Latte,
    image2: Images.Metaballs,
    image3: Images.Seeds,
    category: "Baking material",
    title: "Haagen-Dazs Caramel Cone Ice Cream",
    rating: 2.0,
    brand: "Tyson",
    weight: "473 mL",
    price: "1905.85",
    oldPrice: "2400.80",
    discount: "",
    discountBG: "",
    stockStatus: "In Stock",
    tags: ["ice cream", "caramel", "dessert"],
    text: "Caramel ice cream with crunchy cone pieces.",
    longDescription: "Rich caramel swirl meets crunchy chocolate-coated cone pieces in this indulgent dessert by Haagen-Dazs.",
    shippingInfo: "Handled with cold pack delivery"
  },
  {
    id: 11,
    sku: "SNK-001",
    image: Images.Seeds,
    image2: Images.Metaballs,
    image3: Images.VegPops,
    category: "Fresh Fruit",
    title: "Seeds of Change Organic Quinoa",
    rating: 4.0,
    brand: "NestFood",
    weight: "450g",
    price: "28.85",
    oldPrice: "32.80",
    discount: "HOT",
    discountBG: "#F74B81",
    stockStatus: "In Stock",
    tags: ["organic", "quinoa", "fiber"],
    text: "Organic quinoa packed with fiber and essential nutrients.",
    longDescription: "This organic quinoa is perfect for a healthy lifestyle. Rich in fiber and essential nutrients, it can be served with vegetables or used in salads and other dishes.",
    shippingInfo: "Free shipping for orders over $50"
  },
  {
    id: 12,
    sku: "HDF-002",
    image: Images.Metaballs,
    image2: Images.Seeds,
    image3: Images.Coconut,
    category: "Fruits",
    title: "Italian Style Chicken Meatballs",
    rating: 3.5,
    brand: "Stouffer",
    weight: "1kg",
    price: "52.85",
    oldPrice: "55.80",
    discount: "Sale",
    discountBG: "#67BCEE",
    stockStatus: "In Stock",
    tags: ["meatballs", "chicken", "italian"],
    text: "Juicy, all-natural chicken meatballs seasoned with Italian herbs.",
    longDescription: "Our meatballs are made from natural chicken, seasoned with Italian spices, and ideal for pasta dishes or as a quick protein snack.",
    shippingInfo: "Standard shipping charges apply."
  },
  {
    id: 13,
    sku: "SNK-003",
    image: Images.VegPops,
    image2: Images.BeanNut,
    image3: Images.Butter,
    category: "Pet Foods",
    title: "Boomchickapop Sweet & Salty Popcorn",
    rating: 4.0,
    brand: "StarKist",
    weight: "160g",
    price: "48.85",
    oldPrice: "52.80",
    discount: "New",
    discountBG: "#3BB77E",
    stockStatus: "In Stock",
    tags: ["popcorn", "sweet", "salty"],
    text: "A delicious blend of sweet and salty popcorn.",
    longDescription: "Made with whole grains, Boomchickapop offers the perfect combination of sweet and salty flavors in each kernel.",
    shippingInfo: "Free delivery on first order"
  },
  {
    id: 14,
    sku: "VEG-004",
    image: Images.BeanNut,
    image2: Images.Coconut,
    image3: Images.Metaballs,
    category: "Baking Material",
    title: "Foster Farms Crispy Classic",
    rating: 4.0,
    brand: "NestFood",
    weight: "600g",
    price: "17.85",
    oldPrice: "19.80",
    discount: "",
    discountBG: "",
    stockStatus: "Out of Stock",
    tags: ["veggie", "crispy", "snack"],
    text: "Crispy veggie bites, perfect for quick meals.",
    longDescription: "Foster Farms brings a crispy and savory delight packed with flavors. Serve with sauces or enjoy as-is.",
    shippingInfo: "Restocking soon"
  },
  {
    id: 15,
    sku: "PET-005",
    image: Images.Coconut,
    image2: Images.Seeds,
    image3: Images.Muffin,
    category: "Pet Foods",
    title: "Blue Diamond Lightly Salted Almonds",
    rating: 4.0,
    brand: "Nest Food",
    weight: "200g",
    price: "23.85",
    oldPrice: "25.80",
    discount: "-14%",
    discountBG: "#F59758",
    stockStatus: "In Stock",
    tags: ["almonds", "healthy", "snack"],
    text: "Lightly salted almonds, perfect for guilt-free snacking.",
    longDescription: "Packed with protein and healthy fats, these almonds are ideal for midday snacks or on-the-go munching.",
    shippingInfo: "Express shipping available"
  },
  {
    id: 16,
    sku: "HDF-006",
    image: Images.Muffin,
    image2: Images.Butter,
    image3: Images.VegPops,
    category: "Milks & Dairies",
    title: "Chobani Complete Vanilla Greek Yogurt",
    rating: 4.0,
    brand: "NestFood",
    weight: "170g",
    price: "54.85",
    oldPrice: "55.80",
    discount: "",
    discountBG: "",
    stockStatus: "In Stock",
    tags: ["yogurt", "greek", "protein"],
    text: "High-protein vanilla yogurt with no added sugar.",
    longDescription: "Chobani's Complete Vanilla yogurt is smooth, rich, and fortified with probiotics for better digestion and health.",
    shippingInfo: "Refrigerated shipping ensured"
  },
  {
    id: 17,
    sku: "MLS-007",
    image: Images.Butter,
    image2: Images.Cream,
    image3: Images.OrganicCoffee,
    category: "Baking Material",
    title: "Canada Dry Ginger Ale - 2L Bottle",
    rating: 4.0,
    brand: "Nest Food",
    weight: "2L",
    price: "32.85",
    oldPrice: "33.80",
    discount: "",
    discountBG: "",
    stockStatus: "In Stock",
    tags: ["beverage", "ginger", "carbonated"],
    text: "Refreshing ginger ale perfect for meals or solo drinking.",
    longDescription: "Canada Dry brings a bold ginger flavor that's both refreshing and crisp—great for mixers or on its own.",
    shippingInfo: "Available for local delivery"
  },
  {
    id: 18,
    sku: "SNK-008",
    image: Images.Cream,
    image2: Images.BeanNut,
    image3: Images.Latte,
    category: "Clothing",
    title: "Encore Seafoods Stuffed Alaskan",
    rating: 4.0,
    brand: "Nest Food",
    weight: "500g",
    price: "35.85",
    oldPrice: "37.80",
    discount: "Sale",
    discountBG: "#67BCEE",
    stockStatus: "Limited Stock",
    tags: ["seafood", "stuffed", "alaskan"],
    text: "Flavorful seafood stuffed with rich Alaskan filling.",
    longDescription: "Stuffed Alaskan seafood treats are packed with herbs, breadcrumbs, and a creamy filling that melts in your mouth.",
    shippingInfo: "Ships in insulated packaging"
  },
  {
    id: 19,
    sku: "COF-009",
    image: Images.OrganicCoffee,
    image2: Images.Cream,
    image3: Images.Seeds,
    category: "Clothing",
    title: "Gortons Beer Battered Fish Fillets",
    rating: 4.0,
    brand: "Old El Paso",
    weight: "900g",
    price: "23.85",
    oldPrice: "25.80",
    discount: "Hot",
    discountBG: "#F74B81",
    stockStatus: "In Stock",
    tags: ["fish", "beer battered", "frozen"],
    text: "Crispy beer-battered fish fillets for lunch or dinner.",
    longDescription: "Golden and crunchy, Gortons beer-battered fillets are ideal for tacos, sandwiches, or as a main dish.",
    shippingInfo: "Frozen delivery option required"
  },
  {
    id: 20,
    sku: "CRM-010",
    image: Images.Latte,
    image2: Images.Metaballs,
    image3: Images.Seeds,
    category: "Clothing",
    title: "Haagen-Dazs Caramel Cone Ice Cream",
    rating: 2.0,
    brand: "Tyson",
    weight: "473 mL",
    price: "22.85",
    oldPrice: "24.80",
    discount: "",
    discountBG: "",
    stockStatus: "In Stock",
    tags: ["ice cream", "caramel", "dessert"],
    text: "Caramel ice cream with crunchy cone pieces.",
    longDescription: "Rich caramel swirl meets crunchy chocolate-coated cone pieces in this indulgent dessert by Haagen-Dazs.",
    shippingInfo: "Handled with cold pack delivery"
  }
];

export default PopularProductData;

