import React from 'react'

const Images =  {
  Logo: require("./image.png"),
  CarouselBG1:require("./CarouselBG1.png"),
  CarouselBG2:require("./CarouselBG2.png"),
  Burger:require("./Burger.png"),
  Black_Plum:require("./Black_plum.png"),
  Cabbage:require("./Cabbage.png"),
  Coffee:require("./CoffeeAndTea.png"),
  CustardApple:require("./Custard_Apple.png"),
  Kiwi:require("./Kiwi.png"),
  Peach:require("./Peach.png"),
  RedApple:require("./RedApple.png"),
  Snaks:require("./Snaks.png"),
  Strawberry:require("./Strawberry.png"),
  Add1:require("./Add1.png"),
  Add2:require("./Add2.png"),
  Add3:require("./Add3.png"),
  Seeds:require("./Seeds.jpg"),
  Metaballs:require("./Metballs.jpg"),
  VegPops:require("./VegPops.jpg"),
  BeanNut:require("./BeanNut.jpg"),
  Coconut:require("./Coconut.jpg"),
  Muffin:require("./Muffin.jpg"),
  Butter:require("./Butter.jpg"),
  Cream:require("./Cream.jpg"),
  OrganicCoffee:require("./OrganicCoffe.jpg"),
  Latte:require("./Latte.jpg"),
  FooterBG:require("./FooterBG.png"),
  FooterOverlay:require("./FooterOverlay.png"),
  FooterIcon1:require("./FooterIcon1.png"),
  FooterIcon2:require("./FooterIcon2.png"),
  FooterIcon3:require("./FooterIcon3.png"),
  FooterIcon4:require("./FooterIcon4.png"),
  FooterIcon5:require("./FooterIcon5.png"),
  FooterIcon6:require("./FooterIcon6.png"),
  FooterPayment:require("./FooterPayment.png"),
  FooterAppStore:require("./FooterAppStore.jpg"),
  FooterGooglePay:require("./FooterGooglePay.jpg"),
  LeafBG:require("./LeafBG.png"),
  DealsOfDay1:require("./DealsOfDay1.png"),
  DealsOfDay2:require("./DealsOfDay2.png"),
  DealsOfDay3:require("./DealsOfDay3.png"),
  DealsOfDay4:require("./DealsOfDay4.png"),
  AboutPic:require("./AboutPic.png"),
  Slider1:require("./Slider1.png"),
  Slider2:require("./Slider2.png"),
  Slider3:require("./Slider3.png"),
  Underline:require("./Underline.png"),
  AboutComboPic:require("./AboutComboPic.png"),
  AboutLongPic:require("./AboutLongPic.png"),
  TeamPerson1:require("./TeamPerson1.png"),
  TeamPerson2:require("./TeamPerson2.png"),
  FormImage:require("./FormImage.png"),
  BlogBG:require("./BlogBG.png"),
  Blog1:require("./Blog1.png"),
  Blog2:require("./Blog2.png"),
  Blog3:require("./Blog3.png"),
  Blog4:require("./Blog4.png"),
  Blog5:require("./Blog5.png"),
  Blog6:require("./Blog6.png"),
  Blog7:require("./Blog7.png"),
  Blog8:require("./Blog8.png"),
  Blog9:require("./Blog9.png"),
  Blog10:require("./Blog10.png"),
  Blog11:require("./Blog1.png"),
  Blog12:require("./Blog12.png"),
  Blog13:require("./Blog13.png"),
  Blog14:require("./Blog14.png"),
  Blog15:require("./Blog15.png"),
  BlogHead:require("./BlogHead.png"),
  Blog_Baking:require("./Blog_Baking.png"),
  Blog_Clothing:require("./Blog_Clothing.png"),
  Blog_Fruit:require("./Blog_Fruit.png"),
  Blog_Milk:require("./Blog_Milk.png"),
  Blog_Pet:require("./Blog_Pet.png"),
  Trending1:require("./Trending1.jpg"),
  Trending2:require("./Trending2.jpg"),
  Trending3:require("./Trending3.jpg"),
  Trending4:require("./Trending4.jpg"),
  Blog_Gallery1:require("./Blog_Galllery1.jpg"),
  Blog_Gallery2:require("./Blog_Gallery2.jpg"),
  HeadingPic:require("./HeadingPic.png"),
  BlogDetailsPic:require("./BlogDetailsPic.png"),
  BlogDetailsBody:require("./BlogDetailsBody.png"),
  Comments1:require("./Comments1.png"),
  Comments2:require("./Comments2.png"),
  Comments3:require("./Comments3.png"),
  FilterImg:require("./FilterImg.png"),
  HalfLogo:require("./HalfLogo.png"),
  Grocery:require("./Grocery.avif"),
  Grocery1:require("./Grocery1.jpg"),
  Grocery2:require("./Grocery2.jpg"),







  
}

export default Images