import Images from "../../../Assets/Images";

const RecipiesData = [
  {
    id: 1,
    image: Images.Blog1,
    type: "Healthy",
    title: "The Intermediate Guide to Healthy Food",
    date: "July 4, 2025",
    views: "1.4K",
    readTime: "5 min read",
  },
  {
    id: 2,
    image: Images.Blog2,
    type: "Salad",
    title: "Summer Quinoa Salad Jars with Lemon Dill",
    date: "July 3, 2025",
    views: "980",
    readTime: "3 min read",
  },
  {
    id: 3,
    image: Images.Blog3,
    type: "Chicken",
    title: "Caprese Chicken with Smashed Potatoes",
    date: "July 2, 2025",
    views: "1.2K",
    readTime: "4 min read",
  },
  {
    id: 4,
    image: Images.Blog4,
    type: "Chickpeas",
    title: "Harissa Chickpeas with Whipped Feta",
    date: "July 1, 2025",
    views: "740",
    readTime: "3 min read",
  },
  {
    id: 5,
    image: Images.Blog5,
    type: "Dessert",
    title: "Almond Butter Chocolate Chip  Bars",
    date: "June 30, 2025",
    views: "820",
    readTime: "4 min read",
  },
  {
    id: 6,
    image: Images.Blog6,
    type: "Tacos",
    title: "Smoky Beans & Greens Tacos with Avocado",
    date: "June 29, 2025",
    views: "1.1K",
    readTime: "4 min read",
  },
  {
    id: 7,
    image: Images.Blog7,
    type: "Rice Bowl",
    title: "Sticky Ginger Rice Bowls with Pickled",
    date: "June 28, 2025",
    views: "670",
    readTime: "3 min read",
  },
  {
    id: 8,
    image: Images.Blog8,
    type: "Pasta",
    title: "Creamy Garlic Sun-Dried Tomato Pasta",
    date: "June 27, 2025",
    views: "1.3K",
    readTime: "4 min read",
  },
  {
    id: 9,
    image: Images.Blog9,
    type: "Pizza",
    title: "The Absolute Easiest Spinach & Pizza",
    date: "June 26, 2025",
    views: "980",
    readTime: "5 min read",
  },
  {
    id: 10,
    image: Images.Blog10,
    type: "Rice",
    title: "Sticky Ginger Rice Bowls with Pickles",
    date: "June 25, 2025",
    views: "740",
    readTime: "3 min read",
  },
  {
    id: 11,
    image: Images.Blog11,
    type: "Cookies",
    title: "The Best Soft Chocolate Chip Cookies",
    date: "June 24, 2025",
    views: "860",
    readTime: "4 min read",
  },
  {
    id: 12,
    image: Images.Blog12,
    type: "Rolls",
    title: "Baked Mozzarella Chicken Rolls",
    date: "June 23, 2025",
    views: "930",
    readTime: "4 min read",
  },
  {
    id: 13,
    image: Images.Blog13,
    type: "Salad",
    title: "The Best Avocado Egg Salad",
    date: "June 22, 2025",
    views: "620",
    readTime: "3 min read",
  },
  {
    id: 14,
    image: Images.Blog14,
    type: "Blog",
    title: "The Illigans are on the screen no ",
    date: "June 21, 2025",
    views: "1K",
    readTime: "5 min read",
  },
  {
    id: 15,
    image: Images.Blog15,
    type: "Blog",
    title: "The Illigans are on the screen no one ",
    date: "June 20, 2025",
    views: "1K",
    readTime: "5 min read",
  },
];

export default RecipiesData;
